apiVersion: v1
kind: Namespace
metadata:
  name:  dhl-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhl-api
  namespace: dhl-test
spec:
  selector:
    matchLabels:
      app: dhl-test
  template:
    metadata:
      labels:
        app: dhl-test
    spec:
      containers:
      - name: dhl-api
        env:
        - name:  DB_URI
          valueFrom:
            secretKeyRef:
              name:  db-uri-secret
              key:  DB_URI
        - name: UVICORN_HOST
          value: "0.0.0.0"
        - name: UVICORN_PORT
          value: "8000"
        - name: WEB_CONCURRENCY
          value: "7"
        - name: REMOTE_URL
          value: "51.15.60.207"
        image: ghcr.io/zombeer/dhl_test
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dhl-api-service
  namespace: dhl-test
  labels:
   app: dhl-test
spec:
  type: NodePort
  ports:
    - name: "8000"
      nodePort: 31700
      port: 8000
      targetPort: 8000
  selector:
    app: dhl-test
status:
  loadBalancer: {}